server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: "proyecto-arquitectura-hexagonal"
  devtools:
    add-properties: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/agencia_viajes"
    username: "root"
    password: "0709"
    driverClassName: "com.mysql.cj.jdbc.Driver"

  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
